name: Multi-Env CD Pipeline

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      approve_production:
        description: 'Type YES to approve production deployment'
        required: true
        default: 'NO'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add build steps here (e.g., build docker image, package app, etc.)

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add test steps here (e.g., run pytest, integration tests, etc.)

  deploy_staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request'
    environment:
      name: staging
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to staging..."
      # Add actual deployment steps here

  deploy_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy_staging
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.approve_production == 'YES'
    environment:
      name: production
    steps:
      - name: Deploy to Production
        run: echo "Deploying to production..."
      # Add actual deployment steps here
