name: Multi-Env CD Pipeline

on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add build steps here (e.g., build docker image, package app, etc.)

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add test steps here (e.g., run pytest, integration tests, etc.)

  deploy_staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: staging
      # Set required reviewers in GitHub UI for this environment
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to staging..."
      # Add actual deployment steps here

  deploy_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy_staging
    if: github.event_name == 'workflow_dispatch' # Only allow manual trigger for prod
    environment:
      name: production
      # Set required reviewers in GitHub UI for this environment
    steps:
      - name: Deploy to Production
        run: echo "Deploying to production..."
      # Add actual deployment steps here
