name: Multi-Environment CD Pipeline

on:
  push:
    branches: [dev, uat, main]
  workflow_dispatch:

jobs:
  # Common build and test job for all environments
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        

  # DEV deployment - no approval required
  deploy_dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    needs: build_and_test
    # Only run when changes are pushed to dev branch
    if: github.ref == 'refs/heads/dev'
    environment:
      name: dev
    steps:
      - name: Deploy to DEV
        run: echo "Deploying to DEV environment..."
        # Add your actual deployment steps here

  # UAT deployment - requires manual approval
  deploy_uat:
    name: Deploy to UAT
    runs-on: ubuntu-latest
    needs: build_and_test
    # Only run when changes are pushed to uat branch
    if: github.ref == 'refs/heads/uat'
    environment:
      name: uat
      # The required reviewers are configured in GitHub repository settings
      # This will pause the workflow until approved by a reviewer
    steps:
      - name: Deploy to UAT
        run: echo "Deploying to UAT environment..."
        # Add your actual deployment steps here

  # PROD deployment - requires manual approval
  deploy_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build_and_test
    # Only run when changes are pushed to main branch
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      # The required reviewers are configured in GitHub repository settings
      # This will pause the workflow until approved by a reviewer
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production environment..."
        # Add your actual deployment steps here
